version: '3'
services:
    go-carbon:
        image: go-carbon
        build:
            context: ./go-carbon
        hostname: go-carbon
        container_name: go-carbon
        command: -config=/etc/go-carbon/go-carbon.conf
        volumes:
            - ./configs:/etc/go-carbon
            - ./whisper:/data/graphite/whisper/

    carbonapi:
        image: carbonapi
        build:
            context: ./carbonapi
        hostname: carbonapi
        container_name: carbonapi
        command: -z=http://go-carbon:8080 -graphite=go-carbon:2003 -stdout
        depends_on:
            - go-carbon

    prometheus:
        image: prom/prometheus
        hostname: prometheus
        container_name: prometheus
        volumes:
            - ./configs:/etc/prometheus
            - ./prometheus/:/prometheus
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-storage.local.path=/prometheus'
            - '-storage.local.retention=744h'
        expose:
            - 9090
        depends_on:
            - cadvisor

    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter-loki
        hostname: node-exporter-loki

    cadvisor:
        image: google/cadvisor
        container_name: cadvisor
        hostname: cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        expose:
            - 8080

    grafana:
        image: grafana/grafana
        hostname: grafana
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./grafana:/var/lib/grafana
            - ./logs:/var/log/grafana
        depends_on:
            - carbonapi
            - prometheus

